global:
  scrape_interval: 15s
  scrape_timeout: 15s

scrape_configs:

  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 15s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'clickhouse'
    static_configs:
      - targets:
        - 'clickhouse-node1:9363'
        - 'clickhouse-node2:9364'
        - 'clickhouse-node3:9365'
        - 'clickhouse-node4:9366'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
